# Generated by Django 5.2 on 2025-04-23 13:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_alter_clothes_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='clothes_cart',
            new_name='clothes',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_role',
            field=models.CharField(choices=[('client', 'client'), ('owner', 'owner')], default='клиент', max_length=16),
        ),
        migrations.CreateModel(
            name='ClothesReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('comment', models.TextField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('clothes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clothes_review', to='mysite.clothes')),
            ],
        ),
    ]
