# Generated by Django 5.2 on 2025-04-30 09:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_rename_clothes_cart_cartitem_clothes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clothesreview',
            name='client',
        ),
        migrations.AddField(
            model_name='clothesreview',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_review', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_role',
            field=models.CharField(choices=[('client', 'client'), ('owner', 'owner')], default='client', max_length=16),
        ),
    ]
